Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementApp.Manager;
using UniversityManagementApp.Models;

namespace UniversityManagementApp.Controllers
{
    public class CourseController : Controller
    {
        DepartmentManager aDepartmentManager=new DepartmentManager();
        SemesterManager aSemesterManager=new SemesterManager();
        CourseManager aCourseManager=new CourseManager();

        public ActionResult Save()
        {
            var aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.DepartmentList = aDepartments;
            var aSemesterList = aSemesterManager.GetAllSemester();
            ViewBag.Semesterist = aSemesterList;
            return View();
        }
        [HttpPost]
        public ActionResult Save(CourseModels aCourseModels)
        {
            var aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.DepartmentList = aDepartments;
            var aSemesterList = aSemesterManager.GetAllSemester();
            ViewBag.Semesterist = aSemesterList;
            ViewBag.Message = aCourseManager.SaveCourse(aCourseModels);
            return View();
        }

        
	}
}

Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementApp.Manager;
using UniversityManagementApp.Models;

namespace UniversityManagementApp.Controllers
{
    public class StudentController : Controller
    {

       DepartmentManager aDepartmentManager = new DepartmentManager();
        RegisterStudentManager aRegisterStudentManager = new RegisterStudentManager();
        public ActionResult Index()
        {
            var aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.DepartmentList = aDepartments;
            return View();
        }
        [HttpPost]
        public ActionResult Index(RegisterStudentModel aRegisterStudentModel)
        {
            aRegisterStudentModel.StudentRegNo = aRegisterStudentManager.GeneratedRegNumber(aRegisterStudentModel);
            ViewBag.Message = aRegisterStudentManager.Save_Student(aRegisterStudentModel);
            var aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.DepartmentList = aDepartments;
            return View();
        }
	}
	
}

Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementApp.Manager;
using UniversityManagementApp.Models;

namespace UniversityManagementApp.Controllers
{
    public class TeacherController : Controller
    {
        DepartmentManager aDepartmentManager = new DepartmentManager();
        TeacherManager aTeacherManager=new TeacherManager();
        DesignationManager aDesignationManager=new DesignationManager();

        public ActionResult Save()
        {
            var aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.DepartmentList = aDepartments;
            var aDesignationList = aDesignationManager.GetAllDesignation();
            ViewBag.DesignationList = aDesignationList;
            return View();
        }
        [HttpPost]
        public ActionResult Save(TeacherModel aTeacherModel)
        {
            var aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.DepartmentList = aDepartments;
            var aDesignationList = aDesignationManager.GetAllDesignation();
            ViewBag.DesignationList = aDesignationList;
            ViewBag.Message = aTeacherManager.SaveCourse(aTeacherModel);
            return View();
        }




	}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Soft Unity University Management</title>
    @Styles.Render("~/Content/main.css")
    @Styles.Render("~/Content/animate.min.css")
    @Styles.Render("~/Content/bootstrap.css")
    @Styles.Render("~/Content/responsive.css")
    @Styles.Render("~/Content/font-awesome.css")
    @Styles.Render("~/Content/jquery-ui.css")
    @Styles.Render("~/Content/main.css")




    @Scripts.Render("~/bundles/modernizr")


</head>
<body class="homepage" style="background-color:whitesmoke ">
    <header id="header">
        <div class="top-bar">
            <div class="container">

            </div><!--/.container-->
        </div><!--/.top-bar-->
        <nav class="navbar navbar-inverse" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"> Soft Unity <!--  <img src="images/logo.png" alt="logo">--></a>
                </div>

                <div class="collapse navbar-collapse navbar-right">



                    <ul class="nav navbar-nav">
                        <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Departments <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Save Department", "Save", "Department")</li>
                                <li>@Html.ActionLink("View Department", "ViewDepartment", "Department")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Courses <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Save Course", "Save", "Course")</li>
                                <li>@Html.ActionLink("View Course", "Index", "CourseView")</li>


                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Teachers <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Save Teacher", "Save", "Teacher")</li>
                                <li>@Html.ActionLink("Course Assign To Techer", "Index", "CourseAssign")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Allocaton And Schedule <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Allocate Classrooms", "Index", "AllocateClassRoom")</li>
                                <li>@Html.ActionLink("Class Schedule View", "Index", "ClassScheduleView")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Students <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Register Student", "Index", "Student")</li>
                                <li>@Html.ActionLink("Enroll In A Course", "Index", "EnrollCourse")</li>
                                <li>@Html.ActionLink("Save Result", "Index", "StudentResult")</li>
                                <li>@Html.ActionLink("View Result", "Index", "ViewResult")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Unassign  <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Unassign All Course", "UnAssignAllCourses", "CourseAssign")</li>
                                <li>@Html.ActionLink("Unallocate All Classroom", "UnallocateAllClassRomm", "AllocateClassRoom")</li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div><!--/.container-->
        </nav><!--/nav-->
    </header>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>    
    

    @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)


</body>
</html>