Controllers/CourseAssignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementApp.Manager;
using UniversityManagementApp.Models;

namespace UniversityManagementApp.Controllers
{
    public class CourseAssignController : Controller
    {
        DepartmentManager aDepartmentManager=new DepartmentManager();
        TeacherManager aTeacherManager=new TeacherManager();
        CourseManager aCourseManager=new CourseManager();
        CourseAssignManager aCourseAssignManager=new CourseAssignManager();
        
        public ActionResult Index()
        {
            var aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.DepartmentList = aDepartments;
            return View();
        }
        [HttpPost]
        public ActionResult Index(CourseAssignModels aCousAssignModels)
        {
            var aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.DepartmentList = aDepartments;
            ViewBag.Message = aCourseAssignManager.Save(aCousAssignModels);
            return View();
        }
        public JsonResult GetTeacherByDepartmentCode(string departmentCode)
        {
            var teachers = aTeacherManager.GetAllTeacher(departmentCode);
            var courses = aCourseManager.GetAllCourse(departmentCode);
            var teacherCourses = new { courses = courses, teachers = teachers };
            return Json(teacherCourses, JsonRequestBehavior.AllowGet);
            
        }
        public JsonResult GetCourseByDepartmentCode(string departmentCode)
        {
            var courses = aCourseManager.GetAllCourse(departmentCode);
            return Json(courses, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCourseNameByCourseId(string courseId)
        {
            var courses = aCourseManager.GetAllCourseUsingId(courseId);
            return Json(courses, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetTeacherCredit(int?id)
        {
            var teachers = aTeacherManager.GetTeacherCredit(id);
            var teacherTotalCredit = aTeacherManager.GetteacherRemainingCredit(id);
            var remainingCredit = teachers - teacherTotalCredit;
            var getTeacherCreditAndRemainingCredit = new { teachers = teachers, remainingCredit = remainingCredit, teacherTotalCredit = teacherTotalCredit };
            return Json(getTeacherCreditAndRemainingCredit, JsonRequestBehavior.AllowGet);
        }
        public ViewResult UnAssignAllCourses()
        {
            return View();
        }
        public JsonResult UnAssignCourses(string code)
         {
             var message= aCourseAssignManager.UnAssignAllCourses();
             return Json(message, JsonRequestBehavior.AllowGet);
        }


	}
}

Views/CourseAssign/Index.cshtml
@{
    ViewBag.Title = "Save";
}


<style>
    label.error {
        color: red;
        font-weight: bold;
    }
</style>
<br/>
<div class="wrapper" style="background-color: white;width: 700px;border: 2px solid;margin-left: 200px">
    <form id="CourseSaveForm" method="POST">
        <fieldset class="main_form">
            <legend style="text-align: center; background-color: slateblue">Course Assign To Teacher</legend>

            <div class="form-group">
                <label class="col-md-3 control-label">Department</label>
                <div class="col-md-9">
                    <select class="form-control" id="DepartmentCode" name="DepartmentCode">
                        @{
                            <option value=""> Select Department....</option>
                            foreach (var aDepartment in @ViewBag.DepartmentList)
                            {
                                <option value=@aDepartment.Code> @aDepartment.Name</option>
                            }
                        }
                    </select>
                </div>
            </div>
            <br />
            <br />
            <div class="form-group">
                <label class="col-md-3 control-label">Teacher Name</label>
                <div class="col-md-9">
                    <select class="form-control" id="Id" name="Id">
                        @*'Populate From Ajax'*@
                    </select>
                </div>
            </div>
            <br />
            <br />
            <div class="form-group">
                <label class="col-md-3 control-label">Credit To Be Taken</label>
                <div class="col-md-9">
                    <input id="CredittobeTaken" type="text" name="CredittobeTaken" class="form-control" placeholder="<View>">
                </div>
            </div>
            <br />
            <br />
            <div class="form-group">
                <label class="col-md-3 control-label">Remaining Credit</label>
                <div class="col-md-9">
                    <input id="RemainingCredit" type="text" name="RemainingCredit" class="form-control" placeholder="<View>">
                </div>
            </div>
            <br />
            <br />
            <div class="form-group">
                <label class="col-md-3 control-label">Course Code</label>
                <div class="col-md-9">
                    <select class="form-control" id="CourseId" name="CourseId">
                        @*'Populate From Ajax'*@
                    </select>
                </div>
            </div>
            <br />
            <br />
            <div class="form-group">
                <label class="col-md-3 control-label">Name</label>
                <div class="col-md-9">
                    <input id="CourseName" type="text" name="CourseName" class="form-control" placeholder="<View>">
                </div>
            </div>
            <br />
            <br />
            <div class="form-group">
                <label class="col-md-3 control-label">Credit</label>
                <div class="col-md-9">
                    <input id="Credit" type="text" name="Credit" class="form-control" placeholder="<View>">
                </div>
            </div>
            <br />
            <br />
            <div class="form-group">
                <div class="col-md-12 text-right">
                    <button id="saveButton" type="submit" value="Save" class="btn btn-primary btn-lg">Assign</button>
                </div>
            </div>
            <div class="show_msg"><label>@ViewBag.Message</label></div>
        </fieldset>
    </form>
</div>



@section scripts
{
    <script src="~/Scripts/jquery-2.2.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
   
    <script>
        $(document).ready(function () {
            var teacherAlreadyAssignCredit;
            $("#DepartmentCode").change(function () {
                var departmentId = $("#DepartmentCode").val();
                var json = { departmentCode: departmentId };
                $('#Id').empty();
                $('#CourseId').empty();
                $('#CredittobeTaken').val("");
                $('#RemainingCredit').val("");
                $('#Name').val("");
                $('#CourseName').val("");
                $('#Credit').val("");
               


                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetTeacherByDepartmentCode", "CourseAssign")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),

                    success: function (teacherCourses)
                    {
                        $("#Id").append('<option value="">' + "Select Teacher....." + '</option>');
                        $.each(teacherCourses.teachers, function (key, value)
                        {
                            $("#Id").append('<option value=' + value.Id + '>' + value.Name + '</option>');
                        });
                        $("#CourseId").append('<option value="">' + "Select Course....." + '</option>');
                        $.each(teacherCourses.courses, function (key, value) {
                            $("#CourseId").append('<option value=' + value.Id + '>' + value.Code + '</option>');
                        });
                    },

                });
            });//End Of The Ajax Dropdown Call
            $("#Id").change(function () {
                var id = $("#Id").val();
                var json = { id: id };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetTeacherCredit", "CourseAssign")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (getTeacherCreditAndRemainingCredit) {
                        $("#CredittobeTaken").val(getTeacherCreditAndRemainingCredit.teachers);
                        $("#RemainingCredit").val(getTeacherCreditAndRemainingCredit.remainingCredit);
                        teacherAlreadyAssignCredit = getTeacherCreditAndRemainingCredit.teacherTotalCredit;
                    },
                });
            });         

            $("#CourseId").change(function () {
                var courseId = $("#CourseId").val();
                var json = { courseId: courseId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseNameByCourseId", "CourseAssign")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        $.each(data, function (key, value) {
                            $("#CourseName").val(value.Name);
                            $("#Credit").val(value.Credit);
                        });
                       
                    },
                });
            });


            $("#Credit").focus(function () {
                $(this).blur();
            });
            $("#CredittobeTaken").focus(function () {
                $(this).blur();
            });
            $("#CourseName").focus(function () {
                $(this).blur();
            });
            $("#RemainingCredit").focus(function () {
                $(this).blur();
            });
            $("#CredittobeTaken").focus(function () {
                $(this).blur();
            });
            $("#CourseSaveForm").validate({
                rules: {
                    DepartmentCode: {required: true,},
                    Name: "required",
                    Id: "required",
                    CourseId: "required"

                },
                messages: {
                    DepartmentCode:{required: "Please select department name",},
                    Name: { required: "Please add your department name", },
                    Id: { required: "Please select teacher", },
                    CourseId: { required: "Please select a course" }

                }
            });


            $("#saveButton").on("click", function () {
                var a = parseFloat(teacherAlreadyAssignCredit);
                var b = parseFloat($('#Credit').val());
                var c = a + b;
                var d = parseFloat($('#CredittobeTaken').val());
                if (c > d)
               {
                   
                    if (confirm("Are you sure you want to Save this?"))
                    {
                    }
                    else {
                        return false;
                    }

                }
               
            });
        });
    </script>
    }

Views/CourseAssign/UnAssignAllCourses.cshtml
@{
    ViewBag.Title = "Save";
}

<style>
    label.error {
        color: red;
        font-weight: bold;
    }
</style>
<br/>
<br />

<div class="wrapper" style="background-color: white;width: 700px;border: 2px solid;margin-left: 200px">
    <form id="allocateClassRoomForm" method="POST">
        <fieldset class="main_form">
            <legend style="text-align: center; background-color: slateblue">Unassign All Courses</legend>
            <div class="form-group">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <button id="saveButton" type="submit" value="Unassign All Courses" class="btn btn-primary btn-lg">Unassign All Courses</button>
                </div>
                <div class="col-md-4"></div>
            </div>

            <div class="form-group">
                <div class="col-md-12 text-center">
                    <div class="show_msg">
                        <label id="message">

                        </label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</div>

@section scripts
    {
<script src="~/Scripts/jquery-2.2.0.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery-ui.min.js"></script>
<script src="~/Scripts/jquery-ui-1.11.4.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
   
        <script>

        $("#saveButton").on("click", function () {
            var departmentId = $("#saveButton").val();
            var json = { code: departmentId };

            if (confirm("Are you sure you want unassign all courses ?"))
            {
                $.ajax(
                {
                    type: "POST",
                    url: '@Url.Action("UnAssignCourses", "CourseAssign")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        alert(data);
                    },
                });
            }
            else
            {
                return false;
            }

        });


</script>

}