Controllers/ClassScheduleViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementApp.Manager;

namespace UniversityManagementApp.Controllers
{
    public class ClassScheduleViewController : Controller
    {
        DepartmentManager aDepartmentManager=new DepartmentManager();
        ClassScheduleViewManager aClassScheduleViewManager=new ClassScheduleViewManager();

        public ActionResult Index()
        {
            var aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.DepartmentList = aDepartments;
            return View();
        }
        public JsonResult GetClassScheduleAndClassRoomAllocationListByDepartmentCode(string departmentCode)
        {
            var classScheduleList = aClassScheduleViewManager.GetClassScheduleAndClassRoomAllocationListByDepartmentCode(departmentCode);
            return Json(classScheduleList, JsonRequestBehavior.AllowGet);
        }



	}
}

Views/ClassScheduleView/Index.cshtml
@model IEnumerable<UniversityManagementApp.Models.ClassScheduleViewModels>
@{
    ViewBag.Title = "ViewAssignCourse";

}
<br />
<br />
<br />
<div class="wrapper" style="background-color: white;width: 700px;border: 2px solid;margin-left: 200px">
    
    <fieldset class="main_form">
        <legend style="text-align: center; background-color: slateblue"><strong>View Class Schedule And Room Allocation Information</strong></legend>
        <div class="form-group">
            <label class="col-md-3 control-label" for="fullname">Department</label>
            <div class="col-md-9">
                <select class="form-control" id="DepartmentCode" name="DepartmentCode">
                    @{
                        <option value=""> Select Department....</option>
                        foreach (var aDepartment in @ViewBag.DepartmentList)
                        {
                            <option value=@aDepartment.Code> @aDepartment.Name</option>
                        }
                    }
                </select>
            </div>
        </div>
        <br />
        <br />
        <br />

        <table class="table table-striped table-bordered">
            <thead>
                <tr>

                    <th style="width: 110px;">Course Code</th>
                    <th style="width: 235px;">Name</th>
                    <th>Schedule Info</th>
                </tr>
            </thead>
            <tbody id="table">
                @* Populate from ajax  *@
            </tbody>
        </table>
    </fieldset>
</div>
@section scripts
{
    <script src="~/Scripts/jquery-2.2.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script>
        $(document).ready(function() {
            $("#DepartmentCode").change(function() {
                var departmentId = $("#DepartmentCode").val();
                var json = { departmentCode: departmentId };
                var i = 0;
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetClassScheduleAndClassRoomAllocationListByDepartmentCode", "ClassScheduleView")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function(data) {
                        $('#table').empty();
                        $.each(data, function(key, value) {
                           
                            $("#table").append('<tr><td>' + value.CourseCode + '</td><td>' + value.CourseName + '</td><td>' + value.ScheduleInfo + '</td>  </tr>');
                        });
                    },
                    error: function (error) {
                        alert(" An error occured.");
                        $('#table').empty();
                        $("#table").append('<tr><td>No Data Found</td>  </tr>');
                    },
                });
            });
        });
    </script>

}